### ISSUE TITLE
Conflict with nativescript-google-maps-sdk plugin

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#137]
## Your Environment
* Plugin version: 1.9.0-beta.4
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Samsung J5
* Nativescript version (`tns info`):

✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.0 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 5.1.0 and the latest available version is 5.1.1.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.0 version and is up to date.

---

I've finally got around to upgrading to 1.9.0-beta.4 and NS5 but I'm having some compatibility issues with the [nativescript-google-maps-sdk](https://github.com/dapriett/nativescript-google-maps-sdk) plugin. 

Both plugins work fine separately but when I have them both installed I can not use your plugin. The app crashes with:

    Error: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult

Presumably this is something to do with Google Play Services but since both plugins purport to be compatible with the `project.ext` method of setting the version, I'm not sure which plugin is causing the problem.

I've tried the nativescritp-google-maps-sdk default value:

```
project.ext {
    googlePlayServicesVersion = "+"
}
```

the values mentioned in your documentation:

```
project.ext {
  googlePlayServicesVersion = "11.8.0"
  supportVersion = "27.0.1"
}
```

as well as others but they all result in the same crash. 

Could you shed any light on the cause?

Trimmed log:

```
Gradle build...
         + setting applicationId
******************************************************************
* nativescript-background-geolocation
* - googlePlayServicesVersion: 11.8.0
* - supportLibVersion: 27.0.1
******************************************************************
         + applying user-defined configuration from /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/app/App_Resources/Android/app.gradle
Using support library version 27.0.1
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-background-geolocation-lt/platforms/android/libs/tslocationmanager-2.12.19.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-background-geolocation-lt/platforms/android/nativescript_background_geolocation_lt.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-background-http/platforms/android/nativescript_background_http.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-camera/platforms/android/nativescript_camera.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-google-maps-sdk/platforms/android/nativescript_google_maps_sdk.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-background-fetch/platforms/android/nativescript_background_fetch.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/nativescript-background-fetch/platforms/android/libs/tsbackgroundfetch.aar
         + adding aar plugin dependency: /Users/XXXXXXXXXXX/Documents/clients/XXXXXXXXXXX/app/tabbed-nav/XXXXXXXXXXX/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
(node:1387) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
Installing on device e561d0c4...
Successfully installed on device with identifier 'e561d0c4'.
Refreshing application on device e561d0c4...
Successfully synced application XX.XX.XXXXXX.XXXXXX on device e561d0c4.
ActivityManager: Start proc 30762:XX.XX.XXXXXX.XXXXXX/u0a1812 for activity XX.XX.XXXXXX.XXXXXX/com.tns.NativeScriptActivity
JS: journey-tracking-page onLoaded()
JS: setting odometer 0
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
...
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityRecognitionResult" on path: DexPathList[[zip file "/data/app/XX.XX.XXXXXX.XXXXXX-1/base.apk"],nativeLibraryDirectories=[/data/app/XX.XX.XXXXXX.XXXXXX-1/lib/arm, /data/app/XX.XX.XXXXXX.XXXXXX-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
...
System.err: File: "file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/api.js, line: 779, column: 80
System.err: StackTrace: 
System.err: 	Frame: function:'Api.getAdapter', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/api.js', line: 779, column: 81
System.err: 	Frame: function:'Api.init', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/api.js', line: 760, column: 14
System.err: 	Frame: function:'Api.getAdapter', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/api.js', line: 777, column: 18
System.err: 	Frame: function:'Api.addListener', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/api.js', line: 61, column: 22
System.err: 	Frame: function:'BackgroundGeolocation.addListener', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 129, column: 51
System.err: 	Frame: function:'BackgroundGeolocation.on', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 142, column: 26
System.err: 	Frame: function:'JourneyTrackingViewModel', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/journey-tracking/journey-tracking-view-model.js', line: 58, column: 72
System.err: 	Frame: function:'onLoaded', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/journey-tracking/journey-tracking-page.js', line: 10, column: 31
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'Observable._emit', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
System.err: 	Frame: function:'ViewBase.onLoaded', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 236, column: 14
System.err: 	Frame: function:'View.onLoaded', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 217, column: 35
System.err: 	Frame: function:'Page.onLoaded', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 43, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 90
System.err: 	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
System.err: 	Frame: function:'ViewBase.callLoaded', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 311, column: 14
System.err: 	Frame: function:'ViewBase.loadView', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 439, column: 18
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 434, column: 18
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 642, column: 19
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err: 	Frame: function:'FragmentPagerAdapter._commitCurrentTransaction', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 172, column: 38
System.err: 	Frame: function:'FragmentPagerAdapter.finishUpdate', file:'file:///data/data/XX.XX.XXXXXX.XXXXXX/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 156, column: 18
...
System.err: Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
...
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityRecognitionResult" on path: DexPathList[[zip file "/data/app/XX.XX.XXXXXX.XXXXXX-1/base.apk"],nativeLibraryDirectories=[/data/app/XX.XX.XXXXXX.XXXXXX-1/lib/arm, /data/app/XX.XX.XXXXXX.XXXXXX-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
System.err: 	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
System.err: 	... 91 more
System.err: 	Suppressed: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
System.err: 		at dalvik.system.DexFile.defineClassNative(Native Method)
System.err: 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
System.err: 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
System.err: 		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
System.err: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
System.err: 		... 94 more
System.err: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.location.ActivityRecognitionResult
System.err: 		at java.lang.Class.classForName(Native Method)
System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
System.err: 		... 93 more
System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
ActivityManager: Process XX.XX.XXXXXX.XXXXXX (pid 30762)(adj 0) has died(114,397)
ActivityManager: cleanUpApplicationRecord -- 30762
ActivityManager: removeProcessNameLocked mProcessNames.remove pid=30762 ,hash=6326249 ,name=XX.XX.XXXXXX.XXXXXX

```

Full log: https://gist.github.com/3rror404/5facc1d61ff74a45f8e2c5c65c32fb12

**Comment by christocracy** [comment]
Upgrade to latest version `1.9.1`.

When you see `Error: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult`, it means you're importing a version of `play-services < 11.2.0`.  Btw, the latest version of `play-services:location` is [16.0.0](https://developers.google.com/android/guides/setup).

There is absolutely no reason *not* to use the latest published version.

**Comment by 3rror404** [comment]
Shouldn't `googlePlayServicesVersion = "+"` force the latest version? I'm not very clued up on using Play Services.

**Comment by christocracy** [comment]
Never use version `+`.  Install `1.9.1`

**Comment by 3rror404** [comment]
I've updated to 1.9.1 and still see the same crash.
Even nuked to node_modules, hooks, platforms folders for good measure but still the same.

**Comment by christocracy** [comment]
Note NS's new instructions in `App_Resources/Android/src/app.gradle` for providing gradle `ext` vars:

```
// If you want to add something to be applied before applying plugins' include.gradle files
// e.g. project.ext.googlePlayServicesVersion = "15.0.1"
// create a file named before-plugins.gradle in the current directory and place it there
```

`before-plugins.gradle`
```
project.ext.googlePlayServicesVersion = "16.0.0"
project.ext.supportVersion = "27.0.1"
```

**Comment by 3rror404** [comment]
Thanks Chris. Working now.

Note for future me:

> Create `before-plugin.gradle` in `App_Resources/Android/`

**Comment by 3rror404** [comment]
I created the file in `App_Resources/Android/` at the same level as `app.gradle`, not in the `src` folder. It doesn't work in the `src` folder.
